'use strict';
/**
 * build_env_template.js
 * Generates a sanitized .env.example for Tesla export packages.
 *
 * Includes all relevant env var keys with placeholder values.
 * NEVER writes real values — only documentation and placeholders.
 */

const fs   = require('fs');
const path = require('path');

// Ordered list of env vars to document.
// Empty key entries with a comment are used as section separators.
const ENV_KEYS = [
  { comment: '── System ───────────────────────────────────────────────────────' },
  { key: 'CONFIG_STRICT_MODE',        placeholder: 'false',                   comment: 'Enforce strict config validation at startup (true/false)' },
  { key: 'SYSTEM_NAME',               placeholder: 'Odin',                    comment: 'System display name — falls back to config/system.json if unset' },
  { key: 'OPENCLAW_BIN',              placeholder: 'openclaw',                comment: 'OpenClaw binary path override (default: resolved via PATH)' },
  { key: 'GIT_EMAIL',                 placeholder: 'tesla@openclaw.local',    comment: 'Git author email for Tesla export commits' },
  { key: 'GIT_NAME',                  placeholder: 'Tesla Export Bot',        comment: 'Git author name for Tesla export commits' },

  { comment: '── GitHub ───────────────────────────────────────────────────────' },
  { key: 'GITHUB_TOKEN',              placeholder: 'ghp_your_token_here',     comment: 'GitHub PAT with repo write access — required for push' },
  { key: 'GITHUB_USERNAME',           placeholder: 'your_github_username',    comment: 'GitHub username (used to build remote URLs)' },
  { key: 'GITHUB_REMOTE_ODIN_CORE',   placeholder: '',                        comment: 'Optional: override remote URL for odin-core repo' },
  { key: 'GITHUB_REMOTE_ODIN_AGENTS', placeholder: '',                        comment: 'Optional: override remote URL for odin-agents repo' },

  { comment: '── Discord ──────────────────────────────────────────────────────' },
  { key: 'DISCORD_BOT_TOKEN',         placeholder: 'your_discord_bot_token',  comment: 'Main Odin Discord bot token' },
  { key: 'TESLA_DISCORD_BOT_TOKEN',   placeholder: 'your_tesla_bot_token',    comment: 'Tesla Discord bot token (if Tesla has a dedicated bot)' },

  { comment: '── Telegram ─────────────────────────────────────────────────────' },
  { key: 'TELEGRAM_BOT_TOKEN',        placeholder: 'your_telegram_bot_token', comment: 'Telegram bot token for usage-monitor alerts' },
  { key: 'TELEGRAM_CHAT_ID',          placeholder: 'your_chat_id',            comment: 'Telegram chat ID for usage-monitor alerts' },

  { comment: '── LLM Providers ────────────────────────────────────────────────' },
  { key: 'ANTHROPIC_API_KEY',         placeholder: 'sk-ant-your-key-here',    comment: 'Anthropic API key (for API-key auth, not needed with OAuth)' },
  { key: 'OPENAI_API_KEY',            placeholder: 'sk-your-openai-key',      comment: 'OpenAI API key (optional provider)' },
  { key: 'GROQ_API_KEY',              placeholder: 'your_groq_key',           comment: 'Groq API key' },
  { key: 'MINIMAX_API_KEY',           placeholder: 'your_minimax_key',        comment: 'MiniMax API key' },
  { key: 'KIMI_API_KEY',              placeholder: 'your_kimi_key',           comment: 'Kimi (Moonshot) API key' },
  { key: 'MOONSHOT_API_KEY',          placeholder: 'your_moonshot_key',       comment: 'Moonshot API key alias for Kimi' },
  { key: 'NVIDIA_API_KEY',            placeholder: 'your_nvidia_key',         comment: 'NVIDIA API key for Nemotron models' },
];

/**
 * Build the .env.example file content as a string.
 * @returns {string}
 */
function buildEnvTemplate() {
  const lines = [
    '# .env.example',
    '# Generated by Tesla export — copy to .env and fill in real values.',
    '# NEVER commit .env to version control.',
    '',
  ];

  for (const entry of ENV_KEYS) {
    if (!entry.key) {
      // Section separator
      lines.push('');
      lines.push(`# ${entry.comment}`);
    } else {
      if (entry.comment) lines.push(`# ${entry.comment}`);
      lines.push(`${entry.key}=${entry.placeholder}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Write .env.example to a destination directory.
 * @param {string} destDir - the export temp directory
 * @returns {string} - absolute path of the written file
 */
function writeEnvExample(destDir) {
  const content  = buildEnvTemplate();
  const destPath = path.join(destDir, '.env.example');
  fs.mkdirSync(destDir, { recursive: true });
  fs.writeFileSync(destPath, content, 'utf8');
  return destPath;
}

// ── CLI entrypoint ─────────────────────────────────────────────────────────────
if (require.main === module) {
  const dest = process.argv[2] || '.';
  const p    = writeEnvExample(dest);
  console.log(`Wrote: ${p}`);
}

module.exports = { buildEnvTemplate, writeEnvExample };
