'use strict';
/**
 * validate_export.js
 * Pre-push validation suite for Tesla exports.
 *
 * Checks run in order — first failure halts the sequence.
 * All exports must pass before push is allowed.
 *
 * Checks:
 *   1. Live config/validate.js --strict --compat passes
 *   2. Export directory exists and is non-empty
 *   3. .env.example is present
 *   4. No .env files appear in the export
 *   5. No node_modules in the export
 *   6. No secrets in any exported file (re-scan)
 *   7. All required manifest items are present
 */

const fs     = require('fs');
const path   = require('path');
const os     = require('os');
const { spawnSync } = require('child_process');

const { sanitizeContent, compileRules, RULE_DEFINITION_FILES } = require('./sanitize_export');

const BASE_DIR = path.join(os.homedir(), '.openclaw-odin');

// ── Live config validation ─────────────────────────────────────────────────────

/**
 * Run config/validate.js --strict --compat against the live config.
 * @returns {{ passed: boolean, output: string, checkCount: number }}
 */
function runConfigValidation() {
  const validatorPath = path.join(BASE_DIR, 'config', 'validate.js');
  const result = spawnSync(process.execPath, [validatorPath, '--strict', '--compat'], {
    encoding: 'utf8',
    timeout:  30_000,
    cwd:      BASE_DIR,
  });

  const output     = ((result.stdout || '') + (result.stderr || '')).trim();
  const passed     = result.status === 0;
  const countMatch = output.match(/Passed:\s*(\d+)/);
  const checkCount = countMatch ? parseInt(countMatch[1], 10) : 0;

  return { passed, output, checkCount };
}

// ── Export directory walker ────────────────────────────────────────────────────

function walkExportDir(dir, base, results) {
  base    = base    || dir;
  results = results || [];
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (_) {
    return results;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    const rel  = path.relative(base, full).replace(/\\/g, '/');
    if (e.isDirectory()) {
      walkExportDir(full, base, results);
    } else {
      results.push(rel);
    }
  }
  return results;
}

// ── Main validator ─────────────────────────────────────────────────────────────

/**
 * Validate a prepared export directory before push.
 *
 * @param {string}  exportDir   - temp export directory
 * @param {object}  manifest    - full_export.json or agent_export.json
 * @param {object}  rules       - sanitize_rules.json
 * @param {boolean} skipConfig  - skip config/validate.js (if already run upstream)
 * @returns {{ passed: boolean, checks: Array<{name, passed, detail}> }}
 */
function validateExport(exportDir, manifest, rules, skipConfig) {
  skipConfig = skipConfig === true;
  const checks = [];

  // ── Check 1: Live config validation ────────────────────────────────────
  if (!skipConfig) {
    const cv = runConfigValidation();
    checks.push({
      name:   'config/validate.js --strict --compat',
      passed: cv.passed,
      detail: cv.passed
        ? `${cv.checkCount} checks passed`
        : cv.output.split('\n').filter(l => /✗|FAIL|Failed/.test(l)).join('; ').slice(0, 200),
    });
    if (!cv.passed) return { passed: false, checks };
  }

  // ── Check 2: Export directory exists ───────────────────────────────────
  const dirOk = fs.existsSync(exportDir) && fs.statSync(exportDir).isDirectory();
  checks.push({
    name:   'export directory exists',
    passed: dirOk,
    detail: dirOk ? exportDir : 'Export directory not found',
  });
  if (!dirOk) return { passed: false, checks };

  const allFiles = walkExportDir(exportDir);

  checks.push({
    name:   'export directory non-empty',
    passed: allFiles.length > 0,
    detail: `${allFiles.length} file(s) found`,
  });
  if (allFiles.length === 0) return { passed: false, checks };

  // ── Check 3: .env.example present ─────────────────────────────────────
  const hasEnvExample = allFiles.includes('.env.example');
  checks.push({
    name:   '.env.example present',
    passed: hasEnvExample,
    detail: hasEnvExample ? 'Found' : 'Missing — run build_env_template.js',
  });

  // ── Check 4: No .env files ─────────────────────────────────────────────
  // .env.example is explicitly allowed — it is generated by Tesla and must be present.
  // All other .env variants (.env, .env.local, .env.production, etc.) are forbidden.
  const envFiles = allFiles.filter(f => {
    const base = path.basename(f);
    if (base === '.env.example') return false;  // generated by Tesla — always allowed
    return base === '.env' ||
      /^\.env\.[a-zA-Z]/.test(base) ||
      /(^|\/)\.env$/.test(f);
  });
  checks.push({
    name:   'no .env files in export',
    passed: envFiles.length === 0,
    detail: envFiles.length === 0 ? 'Clean' : `FORBIDDEN: ${envFiles.join(', ')}`,
  });
  if (envFiles.length > 0) return { passed: false, checks };

  // ── Check 5: No node_modules ───────────────────────────────────────────
  const hasNodeModules = allFiles.some(f => f.includes('node_modules/') || f.includes('node_modules\\'));
  checks.push({
    name:   'no node_modules in export',
    passed: !hasNodeModules,
    detail: hasNodeModules ? 'FORBIDDEN: node_modules found' : 'Clean',
  });
  if (hasNodeModules) return { passed: false, checks };

  // ── Check 6: Secret scan on export directory ───────────────────────────
  const compiled   = compileRules(rules);
  let   secretHit  = null;
  let   scanned    = 0;

  for (const relPath of allFiles) {
    if (relPath === '.env.example') continue;        // placeholders are expected
    if (RULE_DEFINITION_FILES.has(relPath)) continue; // pattern definitions, not real secrets
    const fullPath = path.join(exportDir, relPath);
    let content;
    try {
      content = fs.readFileSync(fullPath, 'utf8');
    } catch (_) {
      continue;  // binary
    }
    scanned++;
    const result = sanitizeContent(content, relPath, compiled);
    if (!result.safe) {
      secretHit = result;
      break;
    }
  }

  checks.push({
    name:   'no secrets in exported files',
    passed: !secretHit,
    detail: secretHit
      ? `SECRET DETECTED: ${secretHit.reason} in ${secretHit.file}`
      : `${scanned} text files scanned — clean`,
  });
  if (secretHit) return { passed: false, checks };

  // ── Check 7: Required manifest items present ───────────────────────────
  const requiredItems  = (manifest.items || []).filter(i => i.required);
  const missingItems   = [];

  for (const item of requiredItems) {
    const rel    = item.path.replace(/\/$/, '');
    const exists = allFiles.some(f => f === rel || f.startsWith(rel + '/'));
    if (!exists) missingItems.push(item.path);
  }

  checks.push({
    name:   'required manifest items present',
    passed: missingItems.length === 0,
    detail: missingItems.length === 0
      ? 'All required items present'
      : `Missing required: ${missingItems.join(', ')}`,
  });

  const allPassed = checks.every(c => c.passed);
  return { passed: allPassed, checks };
}

module.exports = { validateExport, runConfigValidation, walkExportDir };
